### ISSUE TITLE
Add containsOnly for Collections

### ISSUE THREAD

**Issue by gabrielittner** [willowtreeapps/assertk#118]
Collection currently has `containsAll` which can have extra elements. It would be useful to have a method that doesn't allow extra elements for Collections. Map already has one: `containsOnly`. I'd like to also use that for Sets or Lists.

List has `containsExactly` which doesn't allow extra elements, but it also enforces ordering which might not always be wanted.

**Comment by martintreurnicht** [comment]
@gabrielittner I've added this in my pull request https://github.com/willowtreeapps/assertk/pull/123

**Comment by osamarao** [comment]
@evant should we close this issue now?
