### ISSUE TITLE
Maybe ravamp soft assertions

### ISSUE THREAD

**Issue by evant** [willowtreeapps/assertk#143]
Remove the concept of 'soft assertions' that don't throw, instead all
assertions throw, and `all` and `assertAll` loop through lambda with a
try/catch. This removes the foot-gun of an assertion maybe running the
rest of the body when it fails, an allows props like `index` and `key`
to return a result and fail with an exception instead of having to take
a lambda.

This has been done in a way to not cause existing code to fail to
compile. Instead, you may not see all exceptions thrown. Deprecated
functions have been kept to guide migration.

Would love some feedback on this, there's some pros/cons to this approach.

# pros:
* Consistent execution model for assertions, ie `fail` and `expected` always throws.
* Failable assertion functions can return a more-specific value ex: `isNotNull()` can return `Assert<T>` for chaining. This means lambdas are not required for these.

Instead of:
```kotlin
assert(foo).isNotNull { contains("bar") }
```

We can have:
```kotlin
assert(foo).isNotNull().contains("bar")
```

* Behavior is consistent between an assertion failure and other exceptions being thrown. They will both stop execution in the lambda and be collected by `assertAll` in the same way.

# cons:
`assertAll`/`all` syntax is uglier

before:
```kotlin
assertAll {
   assert(foo).isEqualTo("one")
   assert(bar).isEqualTo("two")
}
```

after:
```kotlin
assertAll({
    assert(foo).isEqualTo("one")
}, {
    assert(bar).isEqualTo("two")
})
```

This likely means these features will be less-used.

pr: https://github.com/willowtreeapps/assertk/pull/142
prior discussion: https://github.com/willowtreeapps/assertk/issues/132

**Comment by mrk-han** [comment]
I am generally not a fan of soft assertions and, generally, the use of `assertAll()` especially in unit tests. Because of this, I think the readability and chaining which is similar to Assert-j is a good trade off for the cons to the `assertAll()` syntax.

**Comment by evant** [comment]
Another pro of this change, is that we could add [contracts](https://github.com/Kotlin/KEEP/blob/master/proposals/kotlin-contracts.md). ex:
```kotlin
assert(foo).isNotNull()
assert(foo).contains("bar")
```
would this be a valuable thing to support?

**Comment by mrk-han** [comment]
Seems nice to have, and it reminds of asserting that a view `isDisplayed()` before asserting what it contains in Espresso.

**Comment by realdeadfish** [comment]
Haven't looked much into it, but recently stumbled upon [Strikt](https://strikt.io/) and they seem to support both chaining and soft assertions. Maybe its a good idea to to have a look at their implementation or - better - eventually join forces?

**Comment by evant** [comment]
Their solution is to wrap assertion implementations in an object ex:
```kotlin
fun Assertion.Builder<LocalDate>.isStTibsDay() =
  assert("is St. Tib's Day") {
    when (MonthDay.from(it)) {
      MonthDay.of(2, 29) -> pass()
      else -> fail()
    }
  }
```
which is an option, but a much bigger breaking change as all assertions would need to be rewritten. Makes custom assertions a bit more verbose so there is a trade-off there. Also couldn't support contracts if that matters.

**Comment by evant** [comment]
Ok actually playing around with contracts, don't think they could be implemented as I was hoping since there are two functions in the chain. Could work around with something like `assertIsNotNull(foo)` etc, but imo should be removed as a pro from this proposal.

**Comment by evant** [comment]
Added an [alternative solution](https://github.com/willowtreeapps/assertk/pull/154) to this problem if anyone wants to take a look.

**Comment by evant** [comment]
Planning on closing this in favor of the alternative solution proposed above. TLDR: soft assertions are staying but `fail()` and `expected()` will immediately throw. Custom assertions that access the `actual` property will need to be migrated to use the `given` function to continue working with soft assertions.
