### ISSUE TITLE
Consider changing name of top level `assert` method to something that doesn't clash with Kotlin stdlib `assert`

### ISSUE THREAD

**Issue by mkobit** [willowtreeapps/assertk#146]
I've had several teammates frequently run into confusion between assertk's `assert` and the Kotlin stdlib [`assert`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/assert.html). It has been confusing for some team members to see `import assertk.*`, have the imports folded in the editor, or when browsing the tests in the browser to have to cognitively differentiate the different call sites of `assertk`.

I thought I would open this to see what the opinions are around the naming.

**Comment by evant** [comment]
Been back and forth on this a few times. You do have to 'fight' with the IDE a little as auto import will try to prefer kotlin's assert. Though I personally like the shorter name. Would probably change it to `assertThat` to match other similar assertion libs.

**Comment by sedovalx** [comment]
You may add `assertThat` function and delegate it to the existing `assert` one. Personally, I prefer the commonly used `assertThat` name.
