### ISSUE TITLE
Updated from 0.10 to 0.13 and getting java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by NeverwinterMoon** [willowtreeapps/assertk#177]
Getting `java.lang.AssertionError: java.lang.NoClassDefFoundError: org/opentest4j/AssertionFailedError` when running tests with Robolectric and test failure. Works fine when test assertion succeeds though. This wasn't an issue before with the same Robolectric version and 0.10.

Looks like a duplicate of #172.

I did try setting `Preferences | Build, Execution, Deployment | Build Tools | Gradle | Runner | Run tests using: Gradle Test Runner` to no avail.

I am using IntelliJ IDEA 2019.1

But I did try running exactly the same spec as Instrumented Test and the problem was not reproducible.

**Comment by evant** [comment]
Going to close in favor of #172, feel free to leave the info I asked for on there.
