### ISSUE TITLE
is JVM target 1.6 supported?

### ISSUE THREAD

**Issue by christian-draeger** [willowtreeapps/assertk#179]
When I'm trying the following example 

```
fun Assert<Person>.hasAge(expected: Int) = given { actual ->
    if (actual.age == expected) return
    expected("age:${show(expected)} but was age:${show(actual.age)}")
}

assertThat(person).hasAge(10)
// -> expected age:<10> but was age:<18>
```

in a project with compile target 1.8 im getting following error:
![Bildschirmfoto 2019-04-17 um 09 42 56](https://user-images.githubusercontent.com/22223458/56269931-3ee59c80-60f5-11e9-89eb-1e4e2bc84f8e.png)

**Comment by evant** [comment]
That's an interesting one. Can you share your project setup? I assume you are telling kotlin to Target Java 8?

**Comment by christian-draeger** [comment]
Here is the projects pom. 
https://github.com/skrapeit/skrape.it/blob/master/pom.xml
It is using the `kotlin-maven-plugin` without specifying a jvm version. 
From what I understand from the kotlin documentation it should default to jvmTarget 1.6
https://kotlinlang.org/docs/reference/using-maven.html

**Comment by evant** [comment]
Oh I see. Looks like we _are_ targeting 1.8 https://github.com/willowtreeapps/assertk/blob/master/assertk-jvm/build.gradle. If you add that does that fix it for you?

**Comment by christian-draeger** [comment]
since i'm using maven instead of gradle, i can not just copy the part from your gradle build file 

```
compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
```

but i explicitly added the jvm target to be 1.8 by adding the following property to my pom.xml
```
<kotlin.compiler.jvmTarget>1.8</kotlin.compiler.jvmTarget>
```

but with no success. 

I can call all the other assertk functions without any issues. Only the `given` lambda function is making trouble (as seen in my screenshot above).
Furthermore it looks like the error only occurres because assertk's `given` function is an inline function. https://github.com/willowtreeapps/assertk/blob/e70b0ea4439e7cdeca438bc11a27ddb3d0fbefa3/assertk-common/src/main/kotlin/assertk/assert.kt#L46

**Comment by evant** [comment]
Just cloned your project and it seems to be working fine for me without making any changes. Using intellij CE 2019.1. When I go into project structure the target platform is set to 1.8

![Screenshot from 2019-04-20 14-58-35](https://user-images.githubusercontent.com/628930/56461212-db6da000-637c-11e9-8f79-38fc892c9912.png)

**Comment by christian-draeger** [comment]
This was a bit miss leading because intellij's project settings (i'm using IntelliJ IDEA 2018.3.3 Ultimate Edition) have been set to JVM target 1.6 and disregarded the settings from my pom.xml
I thought intellij is considering my pom settings and compiles to 1.8 but but it didn't.

Setting the preferences to JVM target 1.8 fixed the problem:
<img width="680" alt="Bildschirmfoto 2019-04-21 um 14 36 37" src="https://user-images.githubusercontent.com/22223458/56470221-328a7800-6444-11e9-9466-229b0fc571f6.png">

thanks for helping

**Comment by evant** [comment]
Just a note for anyone else seeing this issue. There's no plans to support java 1.6 bytecode. Java 8 is 5 years old now and even android can support it fine these days.

**Comment by karottenreibe** [comment]
For anyone who needs to support Java 6 for older Android devices: You can force gradle to compile only the test code with `jvmTarget="1.8"`. This way, the Android app remains 1.6 compatible but assertk can be used as well. 

```groovy
// assertk needs 1.8 as the target but the main android app needs 1.6 for older devices
// (which is the default)
tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
    if (it.name.contains("Test")) {
        kotlinOptions {
            jvmTarget = '1.8'
        }
    }
}
```

**Comment by evant** [comment]
You can tell the android gradle plugin to desugar java 8 usages to support previous versions of android:
```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```
but yeah what you mentioned would work as well
