### ISSUE TITLE
isEqualToIgnoringGivenFields

### ISSUE THREAD

**Issue by Zomzog** [willowtreeapps/assertk#194]
When some fields are automatically calculated and don't need to be tested it can be useful to have this method. 

For example, when I test something with an embedded database in Spring, I don't care about the value of @Id value.

This is the motivation of PR #175.

**Comment by evant** [comment]
Hm, I guess it could be seen as the opposite of `isEqualToWithGivenProperties`, maybe with the name `isEqualToIgnoringGivenProperties`?

**Comment by evant** [comment]
Renamed and merged
