### ISSUE TITLE
Extracting properties support

### ISSUE THREAD

**Issue by tbradlo** [willowtreeapps/assertk#207]
Extracting is a killer feature of AssertJ. It would be great to add this into AssertK especially this feature is not working with Kotlin in AssertJ (see->https://github.com/joel-costigliola/assertj-core/issues/1499 ). This would cause a lot of people using AssertJ in Java (AssertJ is by default included in SpringBoot) - starting writing Kotlin code - to migrate into AssertK. 

Extracting is making code super readable and clean especially for list of beans e.g:

```
assertThat(persons) <-- collection
      .extracting(Person::name, Person::age, Person::raceName)
      .contains(
            tuple("Boromir", 37, "Man"),
            tuple("Sam", 38, "Hobbit"),
            tuple("Legolas", 1000, "Elf"));
```
No custom comparators writing is required.

**Comment by evant** [comment]
Seams useful, in the meantime you can do something like
```kotlin
assertThat(persons)
  .transform { actual -> Triple(actual.name, actual.age, actual.raceName) }
  .contains(
    Triple("Boromir", 37, "Man"),
    Triple("Sam", 38, "Hobbit"),
    Triple("Legolas", 1000, "Elf")
  )
```
