### ISSUE TITLE
Support for infix function notation

### ISSUE THREAD

**Issue by karolhor** [willowtreeapps/assertk#217]
Hi. I'm wondering if you plan to support kotlin infix function notation https://kotlinlang.org/docs/reference/functions.html#infix-notation. 

It would be great if I could write my tests like this:
```kotlin
assertThat(name) isEqualTo "alice"
assertThat(age) isGreaterThan 20
```

**Comment by evant** [comment]
No plans. It doesn't work when the function takes more than one param and it looks odd with chaining:
```kotlin
assertThat(name).isNotNull() isEqualTo "alice"
```
so you'll end up with a miss-match of infix and non-infix assertions.
