### ISSUE TITLE
Custom Assertion Error?

### ISSUE THREAD

**Issue by geoffreywiseman** [willowtreeapps/assertk#227]
Trying a custom assertion as shown in the readme:
```
data class Person(val age: Int)

fun Assert<Person>.hasAge(expected: Int) {
	assertThat("age", actual.age).isEqualTo(expected)
}
```

IntelliJ shows:
> Using 'actual: T' is an error. Use `given` or `transform` to access the actual value instead.

Does the README need to be updated or am I missing something?

**Comment by evant** [comment]
Yep! The README needs to be updated, it should be
```kotlin
fun Assert<Person>.hasAge(expected: Int) = given { actual -->
  assertThat("age", actual.age).isEqualTo(expected)
}
```

**Comment by evant** [comment]
README fixed. Opted to go with using `prop()` as there is an example right below using `given`
