### ISSUE TITLE
Add Kotlin contracts support

### ISSUE THREAD

**Issue by viartemev** [willowtreeapps/assertk#230]
Would you mind to add Kotlin contracts support?
For example: 
```
val response = client.fetchResponse()
assertThat(response).isNotNull()
assertThat(response!!.channels).isNotEmpty()
```
For this case I need to use `!!`.

**Comment by evant** [comment]
https://github.com/willowtreeapps/assertk/issues/143#issuecomment-434680604
My understanding is it's not possible to add contracts support because there's two methods in the chain. For your example, you can do:

```kotlin
val response = client.fetchResponse()
assertThat(response).isNotNull().prop(Response::channels).isNotEmpty()
```

**Comment by viartemev** [comment]
The problem is more obvious if the response has more than one fields. In this case, it will be:
```
assertThat(response).isNotNull()
assertThat(response!!.channels).isNotEmpty()
assertThat(response.programs).isNotEmpty()
```

I made a simple example:
```
val response = Response(emptyList(), emptyList())
assertThat(response).isNotNull()
assertThat(response.programs).isNotEmpty()
assertThat(response.channels).isNotEmpty()
```
where
```
@ExperimentalContracts
fun <T> Assert<T>.isNotNull(vararg values: T) = given { actual ->
    if (!actual.isNotNull()) return
    expected(":${show(values)} to not contain:${show(actual)}")
}

@ExperimentalContracts
fun Any?.isNotNull(): Boolean {
    contract {
        returns(true) implies (this@isNotNull != null)
    }
    return this != null
}

```
or even you can leave only last `Any?.isNotNull()`

If you don't mind I will create PR for it

**Comment by viartemev** [comment]
There is only one drawback - you need to use this construction with `@ExperimentalContracts` annotation.

**Comment by evant** [comment]
If you can get it working, then yeah go for it!

**Comment by viartemev** [comment]
Prototype for contracts support looks like:
```
val response: TvResponse? = null
assertNotNull(response)
assertThat(response.channels).isNotEmpty()
assertThat(response.programs).isNotEmpty()
```
where assertNotNull looks like:
```
@ExperimentalContracts
fun <T : Any> assertNotNull(actual: T?, message: String? = null): T {
    contract { returns() implies (actual != null) }
    if (actual == null) throw AssertionError()
    return actual
}
```

**Comment by viartemev** [comment]
@evant Is there some way to get assert object, not from transform method? Contracts work only as a top-level function

**Comment by evant** [comment]
Do you mean the actual value? There is not.

**Comment by evant** [comment]
So my understanding is you couldn't get a function sequence like `assertThat(response).isNotNull()` to work, since the check would be in the second function and there's no way to propagate it to the argument of the first. If you think there _is_ a way can you show me an example of that? I can help figuring out how to fit that into the architecture if it is possible.

Another option would be to provide our own `assertNotNull(response)`, but there would have to be a convincing reason to use it over the one that already comes with kotlin.

**Comment by viartemev** [comment]
@evant I agree with you, in this case, the ticket can be closed. Thank you for your time.

**Comment by agoston** [comment]
@evant and if you introduced a form of `assertThat(X, isInstanceOf(Y))` - form? that would be in a single call.

**Comment by evant** [comment]
@agoston If you try to actually implement contracts you'll see how limited they are. Neither of your `isInstanceOf` examples can actually work as you can't call methods on paramters in the contract.  The only way I was able to get it to work is:

```kotlin
inline fun <reified T> assertInstanceOf(actual: Any) {
    contract { returns() implies (actual is T) }
}

assertInstanceOf<Y>(x)
```
For the null case, kotlin-test already has `assertNotNull()` so why not just use that instead?

But there is another problem. assertk allows soft assertions which means code can run after the assertion even if it fails. This means the contract may not even be right.

```kotlin
assertAll {
  assertThat(x).isInstanceOf(Y::class)
  // x may not actually be Y here
}
```

Imo it doesn't make sense to add methods to assertk that don't follow the rest of the library neither in appearance nor semantics.

**Comment by agoston** [comment]
True! I guess we'll have to wait until contracts are improved in Kotlin.
Too bad :( would've been a real nifty feature.

**Comment by erawhctim** [comment]
Related issue on Kotlin's issue tracker: https://youtrack.jetbrains.com/issue/KT-58802/Make-it-so-contract-can-affect-outside-variables
