### ISSUE TITLE
isEqualTo should report when two strings only differ by line endings

### ISSUE THREAD

**Issue by rock3r** [willowtreeapps/assertk#246]
Similarly to [what Truth does](https://github.com/google/truth/blob/dba0b01d8690c6ee4c379fadc2ff28840a302961/core/src/main/java/com/google/common/truth/Platform.java#L128-L145), AssertK should report in the diff when the only differences between two strings which are supposed to be identical are in line breaks — this could save lots of people lots of WTFs :)

**Comment by evant** [comment]
Added a pr to render tabs/newlines in a diff, so ex:

```
expected:<"Test[\r]
"> but was:<"Test[]
"
```

```
expected:<"[    ]Test"> but was:<"[\t]Test">
```
