### ISSUE TITLE
Support nullable properties in isEqualToWithGivenProperties and isEqualToIgnoringGivenProperties

### ISSUE THREAD

**Issue by oliviergauthier** [willowtreeapps/assertk#247]
I need to compare objects excluding some properties that are nullable, 

Can you accept nullable properties in `isEqualToWithGivenProperties` and `isEqualToIgnoringGivenProperties` by changing methods signatures like that : 
fun <T : Any> Assert<T>.isEqualToIgnoringProperties(other: T, vararg properties: KProperty1<T, Any?>) { ... } and fun <T> Assert<T>.isEqualToWithGivenProperties(other: T, vararg properties: KProperty1<T, Any?>) {}

Thanks

**Comment by evant** [comment]
Seems reasonable
