### ISSUE TITLE
Is there anyOf alternative?

### ISSUE THREAD

**Issue by msimko81** [willowtreeapps/assertk#250]
I am adopting assertk in a kotlin project and I cannot find anyOf alternative. 

I would like to check whether at least one assertion is met out of the list of assertions. It is possible to check all of assertions are met using assertThat(...).all {}. 

Does assertk support the scenario? If yes, what is the suggested way of implementing such test?

**Comment by evant** [comment]
This is supported for asserting on lists with `none`, `atLeast`, etc. This could probably be expanded to some sort of `assertThat().any {}`. Would be curious to what the use-cases would be.

**Comment by msimko81** [comment]
The scenario is following:

I would like to check whether at least one of the bean properties is not null. I would like to write something like this: 

`            assertThat(myBean).anyOf {
                prop(SomeBean::prop1).isNotNull()
                prop(SomeBean::prop2).isNotNull()
                prop(SomeBean::prop3).isNotNull()
            }
`

**Comment by evant** [comment]
For now you can accomplish the above by using an iterable assertion, will think about the best way to add what's requested and what's the best way to name everything.

```kotlin
assertThat(listOf(myBean.prop1, myBean.prop2, myBean.prop3)).atLeast(1) { it.isNotNull() }
```

**Comment by evant** [comment]
I do have a question, your example asserts the same thing on each of the props. Is that something we should optimize for? I'm worried that an assertion might get a bit too confusing if it's any of a set of arbitrary assertions. In other words, is there any good use-case for

```kotlin
assertThat(myBean).anyOf {
   prop(SomeBean::prop1).someAssertion()
   prop(SomeBean::prop2).someDifferentAssertion()
}
```

**Comment by msimko81** [comment]
My case is just a business related assertion. Maybe I should define an API method to check that business rule and than just make single assertion in a test.
Anyway, thank you for example how to do that using listOf.

**Comment by evant** [comment]
> Maybe I should define an API method to check that business rule and than just make single assertion in a test.

Yep, I definitely recommend doing it that way. It makes the business rule more clear and codified.

**Comment by msimko81** [comment]
thank you
