### ISSUE TITLE
Recommended strategy for nested nullable?

### ISSUE THREAD

**Issue by geoffreywiseman** [willowtreeapps/assertk#251]
When you're dealing with an object tree with possible nulls, is there a good way of handling that with assertk?

Say you have:
```kotlin
data class Employee(val name: String,  val manager: Employee?)

val employee: Employee
```

So it's easy to check the employee's name:
```kotlin
assertThat( employee.name ).isEqualTo( "Arthur Adams")
```

And it's not that hard to check the employee's manager's name, even though it's starting to feel like a mix of Hamcrest and Assertk:
```kotlin
assertThat( employee.manager )
    .isNotNull()
    .hasProperty<String>( "name", equalTo( "Brian Byrnison" ) )
```

But what about the manager's manager's name? Should I go deeper down the Hamcrest side?
```kotlin
assertThat( employee.manager )
    .isNotNull()
    .hasProperty<Employee>( "manager", allOf( 
        isNotNull(), 
        hasProperty<String>( "name", equalTo( "Chris Cantrell" ) 
    ) 
)
```

Or is there a more assertk-like approach that I'm missing for this kind of assertion?  Custom assertions seem like overkill for walking an object graph.

**Comment by evant** [comment]
Are you sure you are looking at the right assertions lib? we don't have a `hasProperty`. The recommend way to do this is by chaining `prop`

```kotlin
assertThat(employee.manager).isNotNull()
    .prop(Employee::manager).isNotNull()
    .prop(Employee::name).isEqualTo("Chris Cantrell")
```

You mention that customer assertions seem overkill, but they can be useful for commonly accessed properties.

```kotlin
fun Assert<Employee>.manager() = prop(Employee::manager)
fun Assert<Employee>.name() = prop(Employee::name)
```

```kotlin
assertThat(employee.manager).isNotNull()
    .manager().isNotNull()
    .name().isEqualTo("Chris Cantrell")
```

**Comment by geoffreywiseman** [comment]
Yup -- `hasProperty` felt like a mix of Hamcrest because it was mixing in Hamcrest. Not sure where I picked up that habit from, but switching to `prop` feels much more `assertk`-like now. Thanks!
