### ISSUE TITLE
Using Kotlin Contracts for `isNotNull` implementation

### ISSUE THREAD

**Issue by yoelglus** [willowtreeapps/assertk#258]
By using this experimental feature, the compiler can smart cast a nullable value in subsequent assertions. So instead of:
```
val nullString: String? = null
assertThat(nullString).isNotNull().hasLength(4)
```
You can write:
```
val nullString: String? = null
assertThat(nullString).isNotNull()
assertThat(nullString).hasLength(4) // smart cast to String instead of String?
```

**Comment by yoelglus** [comment]
Closing as I realised this is not possible since we will need to make the contract check the `ValueAssert.value` which is not supported by Kotlin Contracts.

**Comment by evant** [comment]
Yep https://github.com/willowtreeapps/assertk/issues/230
