### ISSUE TITLE
Optimize containsExactly output

### ISSUE THREAD

**Issue by nidomiro** [willowtreeapps/assertk#259]
Currently the following line produces the following output:
```kotlin
// loadCalls = [ ["A", "B"] , ["C"], [] ]
assertThat(loadCalls).containsExactly(listOf("A", "B"), listOf("C"))
/* Output:
org.opentest4j.AssertionFailedError: expected to contain exactly:
 at index:2 unexpected:<[]>
*/
```

A more clear output would be printing the contents, like using `isEqualTo`:
```kotlin
// loadCalls = [ ["A", "B"] , ["C"], [] ]
assertThat(loadCalls).isEqualTo(mutableListOf(listOf("A", "B"), listOf("C")))
/* Output:
org.opentest4j.AssertionFailedError: 
Expected :[[A, B], [C]]
Actual   :[[A, B], [C], []]
<Click to see difference>
*/
```

Is it possible to change the output in that way?

**Comment by evant** [comment]
The reason for the current reporting is to better pinpoint the difference when you have large lists. But yeah you probably do want to see the whole lists as well for better context. Been thinking about implementing a better diff output.

**Comment by nidomiro** [comment]
I see two options here:
1. separate Methods for displaying the diff. vs all
2. first print the diff then the Expected/Actual

**Comment by evant** [comment]
Would want to go with something like the second one, don't want to have users have to decided which method they want to use.

**Comment by evant** [comment]
I do want to note that
```
Expected :[[A, B], [C]]
Actual   :[[A, B], [C], []]
<Click to see difference>
```
is special processing that intellij, does. It is not the actual printed exception. We want things to be just as readable inside and outside intellij but think it's important to note for testing implementations.
