### ISSUE TITLE
assertk-0.20.jar not available on mavenCentral()

### ISSUE THREAD

**Issue by ttomasini** [willowtreeapps/assertk#260]
The kotlin version of `assertk` (not `assertk-jvm`) is not available on [mavenCentral()](https://repo1.maven.org/maven2/com/willowtreeapps/assertk/assertk/0.20/).

Is it not available anymore and should one also use `assertk-jvm` for pure Kotlin instead?

**Comment by evant** [comment]
What do you mean by 'pure kotlin'? If you you are running on the jvm, then yes you should use `assertk-jvm`.

**Comment by ttomasini** [comment]
Yes I'm running on the JVM but I'm confused that with v0.10 there was a `assertk` and a `assertk-jvm` package which worked both. With v0.20 the `assertk` package does not contain a jar file anymore. Maybe somebody can clear this up.

**Comment by evant** [comment]
Yeah that change was made to support multiplatform. `assertk` is now the common artifact and `assertk-jvm` is the jvm one. This was mentioned in the [CHANGELOG](https://github.com/willowtreeapps/assertk/blob/master/CHANGELOG.md#011---2018-08-04)

**Comment by lgwillmore** [comment]
I think I am encountering a similar issue - I am trying to use implementation("com.willowtreeapps.assertk:assertk:0.20") in my common source code, but the dependency fails to be imported. I have had to use implementation("com.willowtreeapps.assertk:assertk-common:0.14")

**Comment by evant** [comment]
I've been able to import newer versions into both jvm and common projects with out any issues for a while now. Going to close this. If anyone is having issues please create an issue with a sample project reproducing the problem.
