### ISSUE TITLE
Bump Kotlin to 1.3.60

### ISSUE THREAD

**Issue by saket** [willowtreeapps/assertk#262]
Follow-up of https://github.com/willowtreeapps/opentest4k/pull/9. Can send a PR once that is merged.

**Comment by karottenreibe** [comment]
The linked PR seems to have been merged but no new version of opentest4j has been released thus far. Maybe @evant could do that so that this issue can be resolved by updating the Kotlin and opentest4j version?

**Comment by evant** [comment]
Sorry, didn't have much bandwidth over the holidays, just took a look and almost got it updated. The one issue is that it seems that 1.3.60 requires headless chrome to run js tests so need to figure out how to get that on circle-ci.

**Comment by evant** [comment]
Ok, ci is updated, just need to wait on a day with sonatype feels like not timing out

**Comment by evant** [comment]
Snapshot should be up if you want to test, will get a new version out soonish.
