### ISSUE TITLE
How to unwrap values for custom asserts?

### ISSUE THREAD

**Issue by Kinchkun** [willowtreeapps/assertk#263]
Hi,

I would like to write custom asserts for `javax.ws.rs.core.Response`. Most of it is straightforward. However I would like to assert the body of a response. But before accessing the body a call of `Response::readEntity` is necessary. Can I "fluently" unwrap a value and add an assertion to the resulting value?

E.g.:

```kotlin
assertThat(response).hasBody<MyType>().isDataClassEqualTo(MyType(constructorParam))
```

Where `hasBody` asserts that there is a body available and it can be deserialized to the requested type and then I can add other assertions to the resulting type?

Of course I could write an assert like:

```kotlin
assertThat(response).hasBodyDataClassEqualTo(MyType(constructorParam))
```

However, since the body of a response can be literally of any type, with this approach I need to delegate a lot of asserts.

Cheers

**Comment by evant** [comment]
Not the best documented, but transform https://github.com/willowtreeapps/assertk/blob/beeb72165c1d37dbd6fd618544bbeed707f907ff/src/commonMain/kotlin/assertk/assert.kt#L26 should do what you want. This is used by ex: `index()` to fluently access an item in a collection. https://github.com/willowtreeapps/assertk/blob/beeb72165c1d37dbd6fd618544bbeed707f907ff/src/commonMain/kotlin/assertk/assertions/list.kt#L27

**Comment by evant** [comment]
Alternatively you can try to build it out of higher-level asserts, something like
```kotlin
inline fun <reified T> Assert<Response<T>>.hasBody(): Assert<T> =
    prop("body") { it.readEntity(T::class) /* or however you do this */ }.isNotNull()
```
really depends on how specific you need to be with your error messages.

**Comment by evant** [comment]
Added a bit more info about this to the README

**Comment by Kinchkun** [comment]
Hi,

sorry, I forgot to respond :( Your solution worked fine. Thank you very much!
