### ISSUE TITLE
containsOnly for Array

### ISSUE THREAD

**Issue by evant** [willowtreeapps/assertk#272]
We have it for collections and maps, it's missing for Array.

**Comment by christophpickl** [comment]
PS: there is a `fun Assert<Array<*>>.containsExactly(vararg elements: Any?)` already existing, instead of `containsOnly()`, using kotlin's `contentEquals()` under the hood. it states: "_They must be in the same order and there must not be any extra elements._". IMHO there should be something like `OrderedCollection.containsExactly()` just for the sake of completeness/consistency.

**Comment by evant** [comment]
`containsExactly` does already exist for `List` in addition to arrays, is that what you are talking about?

**Comment by christophpickl** [comment]
yes, `List.containsExactly` is what i'm talking about. but there is no `List.containsOnly`. and i'd have expect it to be defined on iterable, to make it accessable to all the other ordered "things" as well.

PS: how about merging these two `contains*` methods, and have a single one with an (defaulted) argument for `expectOrder` and `mayContainMore` or something similar. reasoning: for me personally it's not really intuitive the difference between "only" and "exactly". this way it would be more explicit. WDYT?

**Comment by evant** [comment]
`List.containsOnly` should exist as `containsOnly` is defined on `Collection` which `List` extends. Unfortunately, I don't think we can define `containsExactly` on iterable, as it doesn't necessarily imply the collection is ordered. For example, `Set` is iterable, but the order isn't defined so an ordered assertion against it would be very brittle.

I don't think overloading a single `contains` method is a good idea, especially since different collections would have different available arguments making it unclear what can do what. I wouldn't be against giving them more intuitive names though.

**Comment by evant** [comment]
I think we _could_ move `containsOnly` from `Collection` to `Iterable` though.

**Comment by evant** [comment]
Created #281 and #282 to track these
