### ISSUE TITLE
IDEA: new string assertions

### ISSUE THREAD

**Issue by christophpickl** [willowtreeapps/assertk#279]
hi all, i've got some ideas around new assertions:

* String.isBase64Encoded
* String.isUuid
* String.isUrl
* String.isOffsetDateTime
* String.isLocalDateTime

what do you think? any feedback would be highly appreciated.

~christoph

```kotlin
private val BASE64_PATTERN = Pattern.compile("^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{2}==)?\$")
fun Assert<String>.isBase64Encoded() {
    given { actual ->
        if (BASE64_PATTERN.matcher(actual).matches()) return
        expected("to be valid Base64 encoded but was: ${show(actual)}")
    }
}
fun Assert<String>.isUuid() {
    given {
        try {
            UUID.fromString(it)
        } catch (e: IllegalArgumentException) {
            expected("to be a valid UUID: ${e.message}")
        }
    }
}
fun Assert<String>.isUrl() {
    given {
        try {
            URL(it)
        } catch (e: MalformedURLException) {
            expected("to be a valid URL: ${e.message}")
        }
    }
}
fun Assert<String>.isOffsetDateTime() {
    given {
        try {
            OffsetDateTime.parse(it, DateTimeFormatter.ISO_OFFSET_DATE_TIME)
        } catch (e: DateTimeParseException) {
            expected("to be a valid ISO offset date time (2019-12-25T17:04:38.59Z): '$it'")
        }
    }
}
fun Assert<String>.isLocalDateTime() {
    given {
        try {
            LocalDateTime.parse(it, DateTimeFormatter.ISO_LOCAL_DATE_TIME)
        } catch (e: DateTimeParseException) {
            expected("to be a valid ISO local date time (2019-12-25T17:04:38.59): '$it'")
        }
    }
}
```

**Comment by evant** [comment]
Hm, not really a fan of these, I feel like it encourages having stringly typed values instead of storing stuff in those actual types. Wouldn't be against having new assertions on `URL`, `LocalDateTime` etc though.

**Comment by christophpickl** [comment]
i see your point, and agree: our models should have proper types, rather than going for "stringly types" 😆 
the reason why i am in need of those is because of writing integration tests against generated data transfer objects (based on JSON) whose types are basically all strings (or numbers/booleans).
if this still goes against the philosophy of assertk, i fully understand. in that case => issue closed 😉

**Comment by evant** [comment]
Json integration tests is an interesting problem space that I don't think assertk is really equipped for, at least not in the core. I'd advise you to look at solutions like [pact](https://github.com/pact-foundation) which imo solve the problem in a better, more useful way.

**Comment by christophpickl** [comment]
thanks for the hint regarding pact, looks good.
"at least not in the core" ... which might be an indicator to have other assertk libs around the core (like hamcrest is doing it).
