### ISSUE TITLE
all + prop failure message

### ISSUE THREAD

**Issue by Kritarie** [willowtreeapps/assertk#287]
It's not clear whether this is a limitation of opentest4j's `MultipleFailuresError`, but the failure message for this specific case could be improved. In my example below, the failure exception is `InvocationTargetException` due to the `KCallable<T>` reflection in `prop`. However, this would seem to apply to any usage of `.all` which 1) produces multiple failures and 2) those failure exceptions contain nested causes.

This code

```kotlin
class RandomTest {

    val factory = RandomThingFactory()

    @Test
    fun testFactory() {
        val thing = factory.maybeCreateRandomThing()
        assertThat(thing).isNotNull().all {
            prop(RandomThing::foo).isEqualTo("foo")
            prop(RandomThing::bar).isEqualTo("bar")
        }
    }
}

class RandomThingFactory {

    fun maybeCreateRandomThing(): RandomThing? {
        return RandomThing()
    }

}

class RandomThing {

    val foo: String get() {
        throw RuntimeException("woah", IllegalArgumentException("the actual reason"))
    }

    val bar: String get() {
        throw RuntimeException("what", IllegalArgumentException("the actual reason"))
    }

}
```

produces this error

```
The following assertions failed (2 failures)
	java.lang.reflect.InvocationTargetException
	java.lang.reflect.InvocationTargetException
org.opentest4j.MultipleFailuresError: The following assertions failed (2 failures)
	java.lang.reflect.InvocationTargetException
	java.lang.reflect.InvocationTargetException
	at test.assertk.RandomTest.testFactory(RandomTest.kt:17)
```

If a call to `.all` produces only a single failure, then the error message includes the full exception trace including the underlying cause.

**Comment by evant** [comment]
Hm, apparently junit 5 uses `Throwable.addSuppressed` to add the exceptions to `MultipleFailuresError`, might be worth investigating.

https://github.com/ota4j-team/opentest4j/issues/35#issuecomment-302077886
https://github.com/junit-team/junit5/blob/master/junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertAll.java

**Comment by evant** [comment]
Tried it out, looks like it works in theory, but gradle breaks it, bah! https://github.com/gradle/gradle/issues/9487

**Comment by evant** [comment]
For `prop(RandomThing::foo)` we can unwrap the `InvocationTargetException`, so that should at least help a bit.

**Comment by evant** [comment]
Added #291 which should make the example error message the following:
```
The following assertions failed (2 failures)
	java.lang.RuntimeException: woah
	java.lang.RuntimeException: what
org.opentest4j.MultipleFailuresError: The following assertions failed (2 failures)
	java.lang.RuntimeException: woah
	java.lang.RuntimeException: what
	at test.assertk.JVMAssertAllTest$RandomTest.testFactory(JVMAssertAllTest.kt:51)
```
