### ISSUE TITLE
`isNotEqualTo` breaks `assertAll` output

### ISSUE THREAD

**Issue by tom-jb** [willowtreeapps/assertk#297]
````kotlin
class Test {
    @Test fun foo() {
        assertAll {
            assertThat(1).isEqualTo(2)
            assertThat(5).isNotEqualTo(5)
        }
    }
}
````
Obviously, both assertions fail, but the output is wrong (tested in Android Studio 3.6.1):

````
org.opentest4j.MultipleFailuresError: The following assertions failed (2 failures)
	org.opentest4j.AssertionFailedError: 
<Click to see difference>
````
I would expect the following output:
````
org.opentest4j.MultipleFailuresError: The following assertions failed (2 failures)
	org.opentest4j.AssertionFailedError: expected:<[2]> but was:<[1]>
	org.opentest4j.AssertionFailedError: expected to not be equal to:<5>
````

(In fact, "expected:<5> not to be equal to:<5>" would be even better for the second line, IMO, but that's a separate topic.)

**Comment by evant** [comment]
How does the output look when run from the commandline? I've noticed Android Studio swallow the error message sometimes.

**Comment by evant** [comment]
Yeah it looks like this is an issue with intellij's <Click to see difference> parsing. It's swallowing up the whole rest of the error message including the other failure!

**Comment by tom-jb** [comment]
Hi. I've just seen your comments. Yeah, it all works fine at the command line.

What's strange is that this problem seems to occur only if the **last** assertion uses `isNotEqualTo`.

For example, if I say `isNotEqualTo` **first** then there's no problem:

````kotlin
class Test {
    @Test fun foo() {
        assertAll {
            assertThat(5).isNotEqualTo(5)
            assertThat(1).isEqualTo(2)
        }
    }
}
````
Output:
````
org.opentest4j.MultipleFailuresError: The following assertions failed (2 failures)
	org.opentest4j.AssertionFailedError: expected to not be equal to:<5>
	org.opentest4j.AssertionFailedError: 
Expected :[2]
Actual   :[1]
<Click to see difference>
````

But if I say `isNotEqualTo` **last** then we're back with the problem:
````kotlin
class Test {
    @Test fun foo() {
        assertAll {
            assertThat(1).isEqualTo(2)
            assertThat(5).isNotEqualTo(5)
        }
    }
}
````
Output:
````
org.opentest4j.MultipleFailuresError: The following assertions failed (2 failures)
	org.opentest4j.AssertionFailedError: 
<Click to see difference>
````

I have a suspicion that Android Studio is getting confused because, if I'm not mistaken, you're not providing two values (i.e., you're saying "it's not equal to 5" rather than "5 is not equal to 5"). I don't know much about your code, though, so I could be complete off here!

**Comment by evant** [comment]
It's not correctly finding the end of the `isEqualTo` error which ends up swallowing the later one. My _guess_ is that the intellij handling here wasn't really designed to handle multiple error messages in the same exception.
> you're not providing two values (i.e., you're saying "it's not equal to 5" rather than "5 is not equal to 5")

unfortunately, that doesn't seem to be the case. I tested locally changing the error message and saw the same behavior.

Btw feel free to open a separate issue about the `isNotEqualTo` error message. My idea with it is that printing the same value twice would always be redundant, but can be convinced to change it.
