### ISSUE TITLE
Double-clicking failing test name in Android Studio doesn't play well with `assertAll` 

### ISSUE THREAD

**Issue by tom-jb** [willowtreeapps/assertk#298]
I realize this may be a problem in Android Studio (3.6.1) and not AssertK, but is there anything AssertK could do here?

**Reproducible steps:**

1. Create this file in a 'test' directory:

````kotlin
// Foo.kt
class Foo {
    @Test fun bar() {
        assertAll {
            assertThat(1).isEqualTo(2)
            assertThat(2).isEqualTo(3)
        }
    }
}
````

2. Run the tests.

3. Double-click the failing test function in the Run tool window.

Android Studio opens File.kt and positions the cursor at the *end of the file*.

Ideally, it would position the cursor at the first failing assertion. And if you remove the `assertAll` block from the above then, of course, it does exactly this.

**Comment by evant** [comment]
Yeah, that's probably because it's the `assertAll` block that ends up throwing the exception that's collected. To see if anything can be done about it, the best way would probably compare with junti5's `assertAll` to see if it's handled any differently.

**Comment by tom-jb** [comment]
Sorry for the late reply!

When I use JUnit 5, double-clicking takes me straight to the method name. The caret goes to the beginning of 'bar' below.

````kotlin
// Foo.kt
class Foo {
    @Test fun |bar() { // | is the caret
        assertAll({
            assertEquals(1, 2)
        }, {
            assertEquals(2, 3)
        })
    }
}
````

**Comment by evant** [comment]
Hm, it looks like it's because `assertAll` is marked inline, seems to confuse intellij here.

**Comment by evant** [comment]
I'm tempted to make `assertAll` not inline. The use-cases for using it that way are fairly limited imo.

**Comment by tom-jb** [comment]
Would that change performance much?

I ask because I think every assertion framework I've used other than yours has quite a slow `assertAll`-type system.

For example, as far as I remember, the equivalent in AssertJ added something like 100 or 200 milliseconds per invocation in some cases.

**Comment by evant** [comment]
I doubt it, but it would be interesting to benchmark.

**Comment by evant** [comment]
Results with jmh:

no assert-all:
```
Result "test.assertk.AssertBenchmarks.assertThat_isEqualTo":
  5.041 ±(99.9%) 0.064 ns/op [Average]
  (min, avg, max) = (4.956, 5.041, 5.210), stdev = 0.086
  CI (99.9%): [4.977, 5.106] (assumes normal distribution)
```

inline:
```
Result "test.assertk.AssertBenchmarks.assertAll_isEqualTo":
  19.987 ±(99.9%) 0.094 ns/op [Average]
  (min, avg, max) = (19.810, 19.987, 20.154), stdev = 0.125
  CI (99.9%): [19.893, 20.081] (assumes normal distribution)
```

non-inline:
```
Result "test.assertk.AssertBenchmarks.assertAll_isEqualTo":
  20.273 ±(99.9%) 1.589 ns/op [Average]
  (min, avg, max) = (16.911, 20.273, 23.824), stdev = 2.121
  CI (99.9%): [18.684, 21.861] (assumes normal distribution)
```

Seems like a negligible difference to me.

**Comment by tom-jb** [comment]
Interesting — thanks for checking that!

The fact that AssertK has fast `assertAll`s is, even on its own, good reason for me to use it. I think it's the only framework I've tried that doesn't add weird lag here.

**Comment by evant** [comment]
Actually, looks like this is fixed. Tested in intellij 2020.2.1 and Android Studio 4.0.1
