### ISSUE TITLE
Assert<T>.prop(KCallable) is not compile-time safe

### ISSUE THREAD

**Issue by alllex** [willowtreeapps/assertk#304]
Currently, the `prop` function is implemented the following way:

```kotlin
fun <T, P> Assert<T>.prop(callable: KCallable<P>) = prop(callable.name) {
    try {
        callable.call(it)
    } catch (e: InvocationTargetException) {
        // unwrap cause for a more helpful error message.
        throw e.cause!!
    }
}
```

In its docs it suggest the following usage:
```kotlin
assertThat(person).prop(Person::name).isEqualTo("Sue")
```

However, the signature of the function accepting `KCallable` is not compile-time safe, because there is no connection between the generic type parameters `T` and `P`.

As a consequence, if one mixes up the property references passed to the `prop` function, the error will occur at runtime. The following snippet, that compiles without errors or warnings, demonstrates the problem.

```kotlin
import assertk.assertThat
import assertk.assertions.isEqualTo
import assertk.assertions.prop

data class Person(val name: String)
data class NotPerson(val notName: String)

fun main() {
    val p = Person(name = "John")
    assertThat(p).prop(NotPerson::notName).isEqualTo("John")
}
```

Running the snipping produces the following result:
```
Exception in thread "main" java.lang.IllegalArgumentException: object is not an instance of declaring class
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
	at kotlin.jvm.internal.CallableReference.call(CallableReference.java:138)
	at assertk.assertions.AnyJVMKt$prop$1.invoke(any.kt:80)
	at assertk.Assert.transform(assert.kt:31)
	at assertk.assertions.AnyKt.prop(any.kt:135)
	at assertk.assertions.AnyJVMKt.prop(any.kt:78)
	at AssertkPropKt.main(AssertkProp.kt:12)
	at AssertkPropKt.main(AssertkProp.kt)
```

In the example I used a reference to a property of a completely unrelated class. This may not happen often, but it still causes the error. A more likely scenario, is when one wants to chain two or more `prop` calls to get to a nested property. This is useful because then the nested name of the assertion is gradually build up by the `prop` functions. In this case accidentally skipping one of the `prop` calls in the chain leads to the runtime error.

In my opinion, the parameter of the `prop` function should be a `KProperty1<T, P>` instead of the `KCallable`. This way there is a clear correspondence between the parent `Assert` and the resulting one, and this correspondence is compile-time checked. Also, replacing the callable by a property still covers the main use-case given in the doc.

If anyone requires to use any other kind of callable, then it is most likely better to use the `prop` function that requires an explicit name and an extractor. This is because other children of the `KCallable` interface do not produce comprehensive names.

The adjustments to the function itself are minor. But I would like to know, whether there was a reason behind choosing `KCallable`?

If not, then I would suggest to deprecate the current implementation and add a more specific one:
```kotlin
fun <T, P> Assert<T>.prop(property: KProperty1<T, P>) = prop(property.name) {
    try {
        property.get(it)
    } catch (e: InvocationTargetException) {
        // unwrap cause for a more helpful error message.
        throw e.cause!!
    }
}
```

Most likely, that upgrading to a new version of AssertK with this implementation will not even break any of the user-code, because they were using it with properties from the start.

**Comment by evant** [comment]
Yeah, I'm inclined to agree here.

**Comment by alllex** [comment]
Great! I will prepare the PR.

**Comment by alllex** [comment]
The PR seems to be ready!

Although, I have a question that may be better discussed before merging.

I think the new overload with `KProperty1` argument should be in the `commonMain`. Some other functions in the `assertk.assertions.AnyKt` already use `KClass` and `KProperty1`, so there should be no problems with that dependency-wise.

The current overload of `prop` function with `KCallable` argument is in the `javaMain`. It is there because its implementation contains a catch of a `InvocationTargetException`. My question is whether it is actually needed to catch this exception.

I tried removing this catch and the tests passed. For example, in the test `test.assertk.assertions.JavaAnyTest#prop_property1_includes_error_message_when_fails` an exception is caught and checked. This exception is the actual exception thrown from `test.assertk.assertions.JavaAnyTest.BasicObject#getFailing`. There was no wrapper in the form of `InvocationTargetException`. So, I presume, that Kotlin reflect operations do not wrap thrown exceptions, at least for the property calls. And in our case, the receiver type is guaranteed to be correct because of bound generics.

So, I propose to remove this catch and move the overload with `KProperty1` to the `commonMain`.

**Comment by evant** [comment]
The try/catch was part of https://github.com/willowtreeapps/assertk/issues/287. If `KProperty1` doesn't wrap the same way as `KCallable` does then no we don't the try/catch. And yes, if it works on all platforms it should go in `commonMain`.

**Comment by alllex** [comment]
It seems that `KProperty1` does not, in fact, wrap the exception.

I reproduced it in the following sample, very similar to the one from #287.
```kotlin
import assertk.Assert
import assertk.all
import assertk.assertThat
import assertk.assertions.isEqualTo
import assertk.assertions.isNotNull
import assertk.assertions.prop
import org.junit.Test
import kotlin.reflect.KCallable
import kotlin.reflect.KProperty1

fun <T, P> Assert<T>.propCallableNoCatch(callable: KCallable<P>) = prop(callable.name) {
    callable.call(it)
}

fun <T, P> Assert<T>.propPropertyNoCatch(property: KProperty1<T, P>): Assert<P> = prop(property.name) {
    property.get(it)
}

class RandomTest {

    val factory = RandomThingFactory()

    @Suppress("DEPRECATION")
    @Test
    fun testFactory() {
        val thing = factory.maybeCreateRandomThing()
        assertThat(thing).isNotNull().all {
            propPropertyNoCatch(RandomThing::foo).isEqualTo("foo")
            propCallableNoCatch(RandomThing::bar).isEqualTo("bar")
        }
    }
}

class RandomThingFactory {

    fun maybeCreateRandomThing(): RandomThing? {
        return RandomThing()
    }

}

class RandomThing {

    val foo: String get() {
        throw RuntimeException("woah", IllegalArgumentException("the actual reason"))
    }

    val bar: String get() {
        throw RuntimeException("what", IllegalArgumentException("the actual reason"))
    }

}
```

The output is
```
The following assertions failed (2 failures)
	java.lang.RuntimeException: woah
	java.lang.reflect.InvocationTargetException: <no message>
org.opentest4j.MultipleFailuresError: The following assertions failed (2 failures)
	java.lang.RuntimeException: woah
	java.lang.reflect.InvocationTargetException: <no message>
	at RandomTest.testFactory(RandomTest.kt:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        ...
```

So in the case of property we get the original exception and in the case of callable we get a wrapped version.
It also means, that the ` test.assertk.assertions.JavaAnyTest#prop_property1_includes_error_message_when_fails` test actually check for the unwrapped exception, if we remove the try/catch from the `prop(KProperty1)` implementation. So, we do not need to introduce new tests.

Once try/catch is removed, there seems to be no other obstacles to moving the new prop function to `commonMain`, because it does not have any platform-specific dependencies.

**Comment by alllex** [comment]
Pull request #305 has been merged.

For the record, the old `prop(KCallable)` was deprecated and the new `prop(KProperty1)` was added to the `commonMain` so it is available on all platforms.
