### ISSUE TITLE
prop() uses deprecated overload when referencing a property from a subtype

### ISSUE THREAD

**Issue by roomscape** [willowtreeapps/assertk#325]
Before the change in #305, I could use `prop` with a property from a subtype, and it would fail if the runtime type didn't match. After the change, it's marked as deprecated.

I'm using Kotlin 1.4.10 with assertk 0.23. Here's a junit test that reproduces my problem.

```kotlin
class OverloadResolution {
    open class A { val a = "test" }
    class B { val b = "test" }
 
    @Test
    fun exampleTest() {
        assertThat(B() as A).all {
            prop(A::a).isEqualTo("test") // OK ✅ 
            prop(B::b).isEqualTo("test") // deprecated ❌ 
        }
    }
}
```
Is this expected? I can see why it doesn't work, and I think I can fix it by adding an `.isInstanceOf` check to narrow the type.

**Comment by roomscape** [comment]
Looks like I've made a small mistake in my example here; let me have another look and try to update it.

**Comment by roomscape** [comment]
I'm also running into the same issue with nullable types.

This used to work, and would fail if `b` was null, but it doesn't work any more.
```kotlin
val b: B? = B()
assertThat(b).prop(B::b)
```
Again, I can easily fix it with an `isNotNull()` check, but I just want to make sure it's deliberate and not an accidental breaking change.

**Comment by roomscape** [comment]
I'm now starting to realise that my examples are instances of exactly the bug (#304) with #305 is intended to fix.

Turns out I have a lot (hundreds) of assertions that I guess were taking advantage of the bug to combine `isNotNull`, `isInstanceOf` and `prop` into a single method call.

**Comment by evant** [comment]
Yep, you got it right, this is deliberate. Before `prop` would take any callable, but now it's tied to the argument type. For migrating, you can always create your own assertions that combine `prop` with `isNotNull`/`isInstanceOf`yourself, if updating hundreds of assertions is an issue.

```kotlin
import assertk.Assert
import assertk.assertions.isInstanceOf
import assertk.assertions.isNotNull
import assertk.assertions.prop as delegateProp
import kotlin.reflect.KProperty1

@JvmName("subclassProp")
inline fun <A: Any, reified B: A, P> Assert<A>.prop(prop: KProperty1<B, P>): Assert<P> = isInstanceOf(B::class)
    .delegateProp(prop)

@JvmName("nullableProp")
fun <T: Any, P> Assert<T?>.prop(prop: KProperty1<T, P>): Assert<P> = isNotNull().delegateProp(prop)
```

After updating your imports to point to these, you can either refactor-rename them if you want to keep using them or refactor-inline them to get rid of them.

**Comment by roomscape** [comment]
Thanks for the response! It makes sense, and your suggestions for migrating are awesome.

The only cases now where I can't find a good solution are when generics are in play. For example, say I have an instance of a parameterised class, but I don't know in my test what the generic type parameter is.

```kotlin
data class Holder<K, V>(val value: Map<K, V>)
val myHolder: Holder<*, *> = Holder(mapOf("a" to "b"))
```
Previously I could have done this:
```kotlin
assertThat(myHolder).prop(Holder<String, String>::value)
    .key("a").isEqualTo("b")
```
Now I have to remove the generic parameter, so I end up with:
```kotlin
assertThat(myHolder).prop(Holder<*, *>::value)
    .key("a").isEqualTo("b") // ❌ doesn't compile
```

Without an unchecked cast there's no way to assert on the contents of the generic map, since `key`, `contains`, etc. are only defined for maps where the type of keys is known.

I wonder if there's anything that could be added to the API to account for cases like this? For now I've ended up replacing my assertions with `.isEqualTo(mapOf(...))`, which, although slightly less expressive, works just fine.

**Comment by evant** [comment]
Hm, you'd almost want a cast operator or something. For now, you can do
```kotlin
assertThat(myHolder)
    .transform { it as Holder<String, String> }
    .prop(Holder<String, String>::value)
    .key("a").isEqualTo("b")
```
or even simpler:
```kotlin
assertThat(myHolder as Holder<String, String>)
    .prop(Holder<String, String>::value)
    .key("a").isEqualTo("b")
```

one tricky thing about this is that because generics are erased it will succeed even if they are wrong:
```kotlin
val myHolder = Holder(mapOf(1 to 2))
assertThat(myHolder as Holder<String, String>)
    .prop(Holder<String, String>::value)
    .key("a").isEqualTo("b")
```
will fail later in the chain after the cast. I don't know of a good way around this.

**Comment by roomscape** [comment]
Actually, thinking about it, the problem I was having could be solved by changing the variance of the `Assert<Map<K, V>>.key(key: K)` function.

The `get` function on a `Map` is defined as `Map<out K, V>.get(key: K): V?`, meaning it's perfectly legal to ask for a key of any type.

```kotlin
val m = mapOf("a" to "b")
println(m[1]) // compiles fine; prints 'null'
```

If the corresponding function in assertk had the same variance, all my problems would be solved. `Assert<Map<out K, V>>.key(key: K)` would let me do this:

```kotlin
assertThat(myHolder)
    .prop(Holder<*, *>::value)
    .key("a").isEqualTo("b")
```

No assertions or type casts required!

**Comment by evant** [comment]
The problem with that is that it breaks type checking when the type is known

```kotlin
assertThat(mapOf("a" to "b")).key(1) // no compile error
```

The `get()` function avoids this by annotating the type with `@kotlin.internal.OnlyInputTypes`, but alas that's an internal kotlin annotation and cannot be used in library code.
