### ISSUE TITLE
Latest version not seen by plugin

### ISSUE THREAD

**Issue by es0329** [willowtreeapps/assertk#328]
I'm seeing interesting logs about assertk when using [this plugin](https://github.com/ben-manes/gradle-versions-plugin), which tracks dependency versions.

To replicate.
- Add assertk to a Gradle project also configured with the Versions plugin.
- Run the task  `./gradlew dependencyUpdates`.

Expectation:
- A report is printed of dependency releases that have drifted ahead of the project.

Observation:
- Attempts to resolve assertk yield a message that `0.23` exceeds the latest, which is believed to be `0.11`. Abbreviated sample report show below.
```
The following dependencies are using the latest milestone version:
 - com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin:0.33.0
 - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.0-M1

The following dependencies exceed the version found at the milestone revision level:
 - com.willowtreeapps.assertk:assertk-jvm [0.23 <- 0.11]
     https://github.com/willowtreeapps/assertk

The following dependencies have later milestone versions:
 - androidx.databinding:viewbinding [4.1.0 -> 4.2.0-alpha14]
```

I'm happy to redirect my report to maintainers of the plugin if needed. I thought to check here first since assertk is the only dependency ever appearing in that "exceeds" section of my reports. All others are either current or behind, as expected.

Keep up the great work! 👍🏽

**Comment by evant** [comment]
Yeah I've seen this before. The reason is that we had originally uploaded to jcenter then stopped. I imagine you have jcenter before mavenCentral in your build.gradle? I tried to get them removed so it would proxy to central instead but I was told it wasn't possible ☹️.

**Comment by es0329** [comment]
Ah, ok. I tried with mavenCentral ahead of jCenter but it's the same result. No biggie; thanks for the reply.

**Comment by ben-manes** [comment]
worst case you could use [repository content filtering](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:repository-content-filtering) to force resolution to Central.
