### ISSUE TITLE
Potential problem with nested all() / any()

### ISSUE THREAD

**Issue by bschelberg** [willowtreeapps/assertk#331]
Problem is described in detail here: https://stackoverflow.com/questions/65207428/assertk-test-shouldnt-pass-nested-alls-any

Along with a link to an example project demonstrating the problem: https://github.com/bschelberg/assertk-test-issue

Essentially, the problem is that a build for that project passes when it should fail.

**Comment by evant** [comment]
Was able to narrow it down to
```kotlin
assertThat(listOf("one")).any {
    it.isEqualTo("two")
    it.isEqualTo("two")
}
```

the problem is that `any` expects an item to fail only once, but there are two failures here, so it messes up the count. Will need to figure out how to properly count failures.
