### ISSUE TITLE
assertThat().isInstanceOf() should support smart cast

### ISSUE THREAD

**Issue by agoston** [willowtreeapps/assertk#343]
When I write `assertThat().isInstanceOf()`, I'd expect that kotlin smart casts are supported and I don't have to do yet another cast in the line that follows.

Is this possible?

**Comment by evant** [comment]
It is not unfortunately https://github.com/willowtreeapps/assertk/issues/230

**Comment by evant** [comment]
Fyi you can chain `isInstanceOf()` so:
```
assertThat(foo).isInstanceOf(Bar::class)
  .prop(Bar::method).isEqualTo("baz")
```

**Comment by agoston** [comment]
But that's not my point. We have a generated REST client that returns a Response, with inner subclasses for different return codes, as per openapi spec.
So there is `Response.Ok` and `Response.BadRequest`, and so on.

Right now, I have to write it like this:

```kotlin
val response = restClient.lookup(...)
assertThat(response).isInstanceOf(Response.BadRequest)
val response2 = response as Response.BadRequest

assertThat(response2.body).isEqualTo(...)
```

You see, there's an extra cast that would not be necessary as assertk already knows perfectly well that it is of that type. If you get a lot of these, it adds up and makes code look convoluted and unoptimal.

**Comment by evant** [comment]
You can write it as

```kotlin
assertThat(response).isInstanceOf(Response.BadRequest::class)
   .prop(Response.BadRequest::body).isEqualTo(...)
```

And if you don't like the look of the prop and are using it a lot, you can factor it out into an extension method

```kotlin
fun Assert<Reponse.BadRequest>.hasBody(body: Any?) = prop(Response.BadRequest::body).isEqualTo(body)

assertThat(response).isInstanceOf(Response.BadRequest::class)
  .hasBody(...)
```

And give me a second, I'm working on a writeup on why if you actually try to implement contracts it doesn't work.

**Comment by agoston** [comment]
yes, one could work it around indeed; i could also make a reified inline function that asserts and casts. But then I'd have to copy that helper method in all my projects, or start a 2-liner library :)
