### ISSUE TITLE
Can't assert index for generic collection

### ISSUE THREAD

**Issue by Bakrog** [willowtreeapps/assertk#376]
Current implementation of function `index` can only be applied to lists.

**Comment by JakeWharton** [comment]
How are you assuming this is implemented for non-random access collections? By walking the iterator N times?

**Comment by lexa-diky** [comment]
I don't think it is a good idea to do this. In JDK [documentation](https://docs.oracle.com/javase/8/docs/api/java/util/Collection.html):

> The root interface in the collection hierarchy. A collection represents a group of objects, known as its elements. Some collections allow duplicate elements and others do not. Some are **ordered and others unordered**. 

For example index of element in `Set<T>` implementations is dependent on various uncontrollable factors and considered undefined a.k.a random.

**Comment by Bakrog** [comment]
I just want to pick an element in a particular index from a generic collection disregarding of the collection particular behaviour. I'm in full control of my tests so I know what to expected (or not).
Just wanted a syntax sugar to make my tests easier to read but let's close this issue and forget about it.

**Comment by evant** [comment]
If you are wondering how to accomplish this, you can convert it to a list which documents that it's now ordered

```kotlin
assertThat(setOf(1, 2).toList()).index(0)
```
