### ISSUE TITLE
Add support for Sequence

### ISSUE THREAD

**Issue by johanhaleby** [willowtreeapps/assertk#378]
Hi, 

I'd like to be able to do assertions on sequences. For example:

```kotlin
val seq = sequenceOf("one", "two")
assertThat(seq).containsOnly("one", "two")
```

But this doesn't compile unless I convert it to an `Iterable`. Would it make sense to explicitly support Sequences?

**Comment by evant** [comment]
Yeah I think that's a good idea. We could have all the same assertions from Iterable
