### ISSUE TITLE
Latest version not published to Maven Central, in spite of what badge says

### ISSUE THREAD

**Issue by toddobryan** [willowtreeapps/assertk#392]
0.24 is the latest version on Maven Central.

If you click the badge, that's what you get. Did the publication of 0.25 fail or something?

**Comment by evant** [comment]
Thanks for the heads up! The badge pulls it's value from maven central so that's certainly strange... will investigate.

**Comment by evant** [comment]
https://repo1.maven.org/maven2/com/willowtreeapps/assertk/assertk/0.25/ it seems to be there, something seems up with search.maven.org?

**Comment by toddobryan** [comment]
Would you like to file an issue with https://github.com/sonatype-nexus-community/search-maven-org/ or would you like me to?

**Comment by evant** [comment]
Done https://github.com/sonatype-nexus-community/search-maven-org/issues/158

**Comment by toddobryan** [comment]
I'll close the issue, since you can still download, but it's really distressing when search.maven.org is wrong. :-O
