### ISSUE TITLE
`isInstanceOf` should be permitted to call on a nullable

### ISSUE THREAD

**Issue by hakanai** [willowtreeapps/assertk#393]
I tried to write the following today:

```kotlin
val extension: Any? = ...;

assertThat(extension).isInstanceOf(WarningsOptionsExtension::class.java)
```

I was surprised that this was not permitted, because the equivalent in Hamcrest would just fail the assertion if the value was `null`.

Workaround is to do it in two steps:

```kotlin
assertThat(extension).isNotNull()
assertThat(extension!!).isInstanceOf(WarningsOptionsExtension::class.java)
```

**Comment by evant** [comment]
You can chain them
```kotlin
assertThat(extension).isNotNull().isInstanceOf(WarningsOptionsExtension::class.java)
```
Hamcrest was written for java which doesn't have nullability in the type system. The explicit `isNull()` assertion makes it so every other assertion doesn't have to check null.

**Comment by hakanai** [comment]
Nice.

**Comment by JakeWharton** [comment]
I would like to propose this be reconsidered.

I'm migrating a few thousand files to AssertK and the need to perform an explicit non-null check before an instance-of check has come up a lot. It feels somewhat asymmetric, especially in comparison to the ability to call `isEqualTo` on a type which is nullable.

Sometimes they appear right next to each other, too:
```kotlin
assertThat(savedState["compositeKeyHash"])
  .isNotNull()
  .isInstanceOf<List<Any?>>()
  .all {
    index(0).isNotNull().isInstanceOf<MutableState<Int>>().prop(MutableState<_>::value).isEqualTo(1)
    index(1).isEqualTo("two")
  }
```

This _could_ be

```kotlin
assertThat(savedState["compositeKeyHash"])
  .isInstanceOf<List<Any?>>()
  .all {
    index(0).isInstanceOf<MutableState<Int>>().prop(MutableState<_>::value).isEqualTo(1)
    index(1).isEqualTo("two")
  }
```

which doesn't feel any less clear. The `is` keyword handles `null` automatically the same way `==` would, so shouldn't `isInstanceOf` handle it the same way `isEqualTo` does?
