### ISSUE TITLE
None Assertion for Iterables seems wrong

### ISSUE THREAD

**Issue by MatthiasGabriel** [willowtreeapps/assertk#396]
Hi,

The none assertions for iterables does not work as I expect it.

The example in the assertion itself it the following:

```
    @Test
    internal fun `should be successful`() {
        assertThat(listOf("one", "two")).none {
            it.hasLength(2)
        }
    }
```

If I now adapt the example, by adding another item `ab` to the list, I'd expect the assertion to fail and the test case described below to be successful, however it fails.

```
    @Test
    public fun `should fail`() {
        assertThrows<AssertionFailedError> {
            assertThat(listOf("one", "two", "ab")).none {
                it.hasLength(2)
            }
        }
    }

```

In the initial pr https://github.com/willowtreeapps/assertk/pull/190 its also mentioned that it should behave as `noneMatch` in AssertJ

Therefore I compared the unit tests of your codebase against the behaviour of AssertJ.

One of the unit tests of the assertk code base:
```
    @Test fun each_non_matching_content_passes() {
        assertThat(listOf(1, 2, 3) as Iterable<Int>).none { it.isLessThan(2) }
    }
```

The unit test adapted to AssertJ, which throws an AssertionError, as expected by me.
```
   @Test
    void each_non_matching_content_passes() {
        assertThatThrownBy(() -> {
                Iterable<Integer> integers = newArrayList(1, 2, 3);
                assertThat(integers).noneMatch(s -> s < 2);
            }
        ).isInstanceOf(AssertionError.class);
    }
```

Thanks for having a look at it.

**Comment by evant** [comment]
Should be fixed by https://github.com/willowtreeapps/assertk/pull/437
