### ISSUE TITLE
chainable iterable assertions

### ISSUE THREAD

**Issue by wjtk** [willowtreeapps/assertk#398]
Just asking - is there any reason that iterable assertions aren't chainable?
Why I cannot test sth like:
```
assertThat(list)
  .hasSize(5)
  .contains(A)  
```

Of course I can use `all` and make soft assertions... but why?

**Comment by evant** [comment]
https://github.com/willowtreeapps/assertk/discussions/346

**Comment by wjtk** [comment]
ok, thx. I forgot about `apply`.
