### ISSUE TITLE
Add is(Not)SameInstanceAs assertions

### ISSUE THREAD

**Issue by dzirbel** [willowtreeapps/assertk#412]
I'd like to have assertions for whether an object is the same instance (or not) as another; this can be helpful for example in situations where you want to ensure extraneous objects aren't being allocated. Google Truth [provides](https://github.com/google/truth/blob/3c580fc7971d85ba3b0b642310b29f101a7451c7/core/src/main/java/com/google/common/truth/Subject.java#L267) this as a base assertion where I found it helpful in the past.

I have an [implementation](https://github.com/dzirbel/kotify/blob/3c44ef2ba43d5c037b768e53f2218361ba63c5ac/src/testFixtures/kotlin/com/dzirbel/kotify/Assertions.kt#L23) which works for me, but I think it's sufficiently general to consider including in the library. I'd be happy to put up a PR but wanted to check what the team thinks first.

**Comment by JakeWharton** [comment]
This is already available as `isSameAs` and `isNotSameAs`. The implementation uses `===` which is instance equality not structural equality.

**Comment by dzirbel** [comment]
Ah, great! I think I must have just searched for functions with `instance` in the name.
