### ISSUE TITLE
New assertion: `containsMatch`

### ISSUE THREAD

**Issue by JakeWharton** [willowtreeapps/assertk#452]
A mixture of `contains` and `match`, but only looks for a match within the string rather than against the whole thing.

Implementation is basically `matchesPredicate(regex::containsMatchIn)`, but it's nice to not have to do that every time you want to switch from an exact `contains` to a fuzzy, regex-based one (or similarly, from matching the whole string to only part of a string).

**Comment by evant** [comment]
You could also change your matching regex to match the whole thing but yeah I could see how this could be simpler.

**Comment by evant** [comment]
Ah yeah multiline regex can get weird
