### ISSUE TITLE
Checksum Assertions

### ISSUE THREAD

**Issue by evant** [willowtreeapps/assertk#55]
Opening this issue to discuss #47. Open questions:
1. Is this common enough to be in the core lib?
2. What checksums/hashes should be supported?
3. What should be the hashed format (byte array, hex string, etc.)?

**Comment by dibog** [comment]
Regarding 3: I'm for any format which can be expressed easily in the test code and is easy
to compare. so any string representation would be fine for me. Some separator between
bytes helps with the readability.

**Comment by nishtahir** [comment]
Hmm. I don't know of a common use case for this. Does anyone know of similar checksum assertions implemented in any other assertions libraries?

**Comment by evant** [comment]
Don't think there's much demand for this, closing for now.
