### ISSUE TITLE
Support for comparing Java Strings (nullable)

### ISSUE THREAD

**Issue by jakubvimn** [willowtreeapps/assertk#58]
Given the Java class (with platform types):
`class Parson { public String name; }`
the following code
`assert(new Person().name).isEqualTo(new Person().name)`
picks the 'isEqualTo' from _strings.kt_, which requires not null type and fails with exception.
Adding a new method for the `String?` type should resolve the problem.
`fun Assert<String?>.isEqualTo(expected: String?)`

**Comment by evant** [comment]
Oh that's interesting, it really won't let you pick `fun <T> Assert<T>.isEqualTo(expected: Any?)` over `fun Assert<String>.isEqualTo(other: String, ignoreCase: Boolean = false)`?

**Comment by jakubvimn** [comment]
The only way for picking the method I want that I found was an explicit cast to `Any?`, but that looked really bad. Maybe the method without the default param would help. I don't know any official Kotlin documentation about signature matching with Java types.
