### ISSUE TITLE
Support for comparing objects that don't have proper equals method

### ISSUE THREAD

**Issue by jakubvimn** [willowtreeapps/assertk#59]
I want to check that some objects that don't have a proper equals method have the same content. What would be the best way of handling that? Assertj contains methods for field-by-field comparison, but I don't see anything like that here.
Writing a custom assertion for every such object requires a lot of boilerplate for the case when both are null, or one of them is not. I've created a helper method for it:

```
   fun <T : Any> Assert<T?>.isEqualToNullSafe(expected: T?, nullSafeAssertion: Assert<T>.(nullSafeExpected: T) -> Unit) {
        val actual = this.actual

        if (actual == null && expected == null) {
            return
        }

        if (actual != null && expected != null) {
            assert(actual).nullSafeAssertion(expected)
        } else {
            fail(expected, actual)
        }
    }
```

with usage like that:

```
     fun Assert<Bundle?>.isEqualTo(expected: Bundle?) {
         isEqualToNullSafe(expected) { nullSafeExpected ->
             assert(actual.keySet()).hasSameSizeAs(nullSafeExpected.keySet())
 
             for (key in actual.keySet()) {
                assert(actual.get(key)).isEqualTo(nullSafeExpected.get(key))
             }
         }
     }
```

Maybe a similar method should be added to the library?

**Comment by evant** [comment]
We are planning on an annotation processor to generate field assertions for a class, ex:

assert(

**Comment by evant** [comment]
We are planning on an annotation processor to generate field assertions for a class, ex:

```
assert(person) {
  name().isEqualTo("...")
  age().isGreaterThan(...)
}
```
is this sufficient? Maybe some other overridable concept of equals would be nice.

Note: for something like bundle, we are planning on having an android-specific artifact in the future.

**Comment by jakubvimn** [comment]
That's promising. I'm looking forward to it :)

**Comment by evant** [comment]
Just an update in case anyone else stumbles across this. The annotation processors isn't happening anytime soon if ever. However there's a few things you can do now:

There's a `prop` function to assert on properties:
```kotlin
assert(person) {
  prop(Person::name).isEqualTo("...")
  prop(Person::age).isGreaterThan(...)
}
```

`isEqualToWithGivenProperties` can compare a subset of properties:
```kotlin
assert(person1).isEqualToWithGivenProperties(person2, Person::name, Person::age)
```

**Comment by evant** [comment]
I _think_ we have most use-cases covered? I actually haven't run into many cases myself where I need to deal with null boilerplate. For example, I'd write something like this to check the contents of a bundle:

```kotlin
fun Assert<Bundle>.containsOnly(vararg elements: Pair<String, *>) = given { actual ->
    assertThat(actual.toMap()).containsOnly(*elements)
}

private fun Bundle.toMap() : Map<String, Any?> = mutableMapOf<String, Any?>().also { map ->
    for (key in keySet()) {
        map[key] = get(key)
    }
}

assertThat(bundle).containsOnly(
    "one" to 1,
    "two" to "two"
)
```

I'm going to close this issue. Let me know if I'm missing anything.
