### ISSUE TITLE
Shorter isEqualTo

### ISSUE THREAD

**Issue by evant** [willowtreeapps/assertk#60]
Since `isEqualTo` is used in like 90% of cases, should it be shorter (or at least have a shorter option?)

ex:

```
fun Assert<T>.eq(expected: Any?) { ... }
fun Assert<T>.neq(expected: Any?) { ... }
```

**Comment by jakubvimn** [comment]
I think it may be a little bit controversial (Uncle Bob wouldn't approve), so I think that it's better not to remove the original name. Having both versions should be a reasonable choice.

**Comment by evant** [comment]
I'm not opposed to keeping both, though that does bring up which we use in documentation, etc. "(Uncle Bob wouldn't approve)", curious what the argument here is.

My argument for: it's a common operation so we can allow for a bit of conciseness over understandably, shouldn't be hard to learn the meaning.

**Comment by jakubvimn** [comment]
I refer here to the book "Clean Code" by Robert C. Martin (aka "Uncle Bob"), chapter 2 "Meaningful names". I don't have the book with me to refer exactly to some paragraphs, but generally he explains why he encourages to use longer and more descriptive names instead of shorter forms or acronyms.

**Comment by rf43** [comment]
fwiw, I feel like `.eq()` and `.neq()` are not very obvious as to what their operations are whereas `.isEqualTo()` and `.isNotEqualTo()` are, especially to the casual observer (think code reviews)

**Comment by dibog** [comment]
+1 to @rf43 reasoning

**Comment by evant** [comment]
Seems like there isn't much interest in supporting this, closing for now.
