### ISSUE TITLE
Consider using Ota4j exceptions (like AssertionFailedError) to better work with JUnit 5 based frameworks

### ISSUE THREAD

**Issue by mkobit** [willowtreeapps/assertk#70]
See https://github.com/ota4j-team/opentest4j

One thing to consider also is _will assertk support multiplatform project_ which may also influence this decision.

**Comment by evant** [comment]
Thanks for the heads up about that project! I definitely like the idea though it says it's still in draft?

We are considering supporting multi-platform projects, though that's still up in the air. It should be doable even with that, as we can have different exception impl's, per-platform.

**Comment by mkobit** [comment]
Interesting, 1.0.0 was published and is part of the current JUnit 5 release. I'll follow up and see what they say.

**Comment by mkobit** [comment]
I asked on the JUnit 5 https://gitter.im/junit-team/junit5 and got an answer that says the draft wording is outdated. I opened https://github.com/ota4j-team/opentest4j/issues/40 to them.

**Comment by evant** [comment]
Thanks for the follow up, will look into implementing it.

**Comment by mkobit** [comment]
I can take a poke at this after the multi-platform stuff is merged in
