### ISSUE TITLE
isEqualTo signature

### ISSUE THREAD

**Issue by evantill** [willowtreeapps/assertk#72]
What about changing isEqualTo signature ?
actually:
```isEqualTo signature  fun <T> Assert<T>.isEqualTo(expected: Any?)```

proposal:
```isEqualTo signature  fun <T> Assert<T>.isEqualTo(expected: T)```

In my case, It would help when refactoring code to have a more precise signature.

**Comment by evantill** [comment]
Actually, I will not have the expected behaviour as the generic argument type ```T``` is defined as covariant.
Is there any reason not to use an invariant type ?

actual:
```class Assert<out T>```

proposal:
```class Assert<T>```

**Comment by evant** [comment]
One thing to note is an `equals` implementation does not require the objects to be the same type (it's signature is `equals(other: Any?)`. I'm not sure how common that actually is but I would be hesitant to preclude that usage.

**Comment by evant** [comment]
Also both [assertj](https://joel-costigliola.github.io/assertj/assertj-core.html) and [truth](https://github.com/google/truth) take object as the type here as well. I totally understand wanting changes to fail at compile time but it will make those tests fail so it's not too bad?

**Comment by evantill** [comment]
I have started to work on it to better understand it.

https://github.com/evantill/assertk/tree/feature/typesafe-isequal

**Comment by evant** [comment]
https://github.com/willowtreeapps/assertk/issues/58 for reference on that string test

**Comment by evantill** [comment]
the string test give me an ```IllegalStateException``` exception

```java.lang.IllegalStateException: JavaNullableString.string() must not be null```

Which is kotlin itself complaining about the null value. The same exception on a simple assignment
```val other:String = JavaNullableString.string()```

In fact, kotlin require us to clarify the type ```T!```is it a ```T``` or a ```T?```

The string test would be :
```
val actual : String? = JavaNullableString.string()
val other : String? = JavaNullableString.string()
assert(actual).isEqualTo(other)
```

**Comment by nishtahir** [comment]
The core issue with this is that you are making the assumption that you will always be checking for equality against the same type. If you the signature of the [equals](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-any/equals.html) method. It is perfectly valid to have code like this

```kotlin
class GenericClass {
    override fun equals(other: Any?): Boolean {
        return when (other) {
            is OtherGenericClass -> this.customCompareLogic(other)
                ... 
        }
    }
}
```

If we constrain `isEqualTo` to accept only `<T>` it breaks cases where you'd want to test custom equality logic

**Comment by evantill** [comment]
@nishtahir do you have real cases where you unit test equality with objects that are not of the same type

Sorry I did not understand the point in your example. Can you elaborate ?

**Comment by evantill** [comment]
@nishtahir  let me clarify that my assumption is only on assertion of equality not in general.
Have you seen unit test that assert equality on some object with unrelated type ?

**Comment by evantill** [comment]
If I take this exemple from the readme :

```kotlin
import assertk.assert
import assertk.assertions.*

class PersonTest {
    val person = Person(name = "Bob", age = 18)

    @Test
    fun testName() {
        assert(person.name).isEqualTo("Alice")
        // -> expected:<["Alice"]> but was:<["Bob"]>
    }

    @Test
    fun testAge() {
        assert("age", person.age).isGreaterThan(20)
        // -> expected [age] to be greater than:<20> but was:<10>
    }
}
```

If during a refactoring, I change person.age type to String, I would expect the compiler to complain on type mistmatch on my assertions.

**Comment by evantill** [comment]
@evant [hamcrest](http://hamcrest.org/JavaHamcrest/javadoc/1.3/org/hamcrest/core/IsEqual.html#equalTo(T)) signature is `<T> Matcher<T> equalTo(T operand)`

**Comment by nishtahir** [comment]
Here's a trivial but slightly more fleshed out example to illustrate my point

```kotlin
class Point2(val x: Int, val y: Int)

class Point3(val x: Int, val y: Int, val z: Int) {
    override fun equals(other: Any?): Boolean {
        return when (other) {
            is Point3 -> (x == other.x && y == other.y && z == other.z)
            is Point2 -> (x == other.x && y == other.y && z == 0 /*or whatever your origin is*/)
            else -> false
        }
    }
}
```

Notice how `Point3` overrides equals with custom equality logic checking for different types. Now if I was writing a test for this my assertion here would look something like this

```kotlin
assert(Point3(1, 2, 0)).isEqualTo(Point2(1, 2))
```

Under your proposal I shouldn't be able to do this, because we would be constraining `isEqualTo` to just the given type in the assertion.

I understand this doesn't work well with refactoring, but I don't think the right solution is to break some core functionality which supports a valid use case in order to fix it.

**Comment by evant** [comment]
So it looks like other assertion libs are split on this:

`isEqualTo(other: Any?)`: assertj, truth
`isEqualTo(other: T)`: hamcrest, fest

I guess the question is what's more important, the common case of same types, or being flexible for all valid use cases?

**Comment by rf43** [comment]
Perhaps it might be better to handle whatever the general understood use case would be for the method (same types) and then have another one (different types) where you could  compare passing in some `Any?` object?

**Comment by evantill** [comment]
@nishtahir  thank you for your clarification.
IMHO Overriding equals like that is more a code smell than a best practice.

**Comment by nishtahir** [comment]
I think supporting both use cases is a good idea. Unfortunately, this opens up another can of worms with questions like what the default should be and how to appropriately name the methods etc. 

> Perhaps it might be better to handle whatever the generally understood use case would be for the method (same types) and then have another one (different types) where you could compare passing in some Any? object?

@rf43 preliminary polling that we've done on this issue has been very onesided (13: 1) in support for `isEqualTo(other: Any?)` as the default behavior.

**Comment by rf43** [comment]
@nishtahir make that 14:1 lol 😂 

I personally like the `isEqualTo(other: Any?)` because of exactly what you said but I can totally see @evantill's point about simply wanting to test two of the same type.

I'm down with either choice, leaning toward making it do whatever the general user would expect from the method.

**Comment by evantill** [comment]
Have you some example of big open source projects using assertk ? I would like to test using equal(T) on it ?

**Comment by evant** [comment]
I don't unfortunately.

**Comment by evant** [comment]
Note: I played around with this a bit more as the signature has bitten me a few times and we do have precidence with kotlin's `assertEquals`. Unfortantly, because of the covaraint type param it doesn't really help, and the coveraince is pretty nice in other circumstances so I don't want to get rid of of. This means this is blocked by the same issue as https://github.com/willowtreeapps/assertk/issues/2.
