### ISSUE TITLE
Make assertk platform independent

### ISSUE THREAD

**Issue by FaustXVI** [willowtreeapps/assertk#75]
Since Kotlin can run on the JVM and Javascipt (and soon native), what about making assertk platform independent too ?

Specific platform assertion could be shipped in platform specific dependencies.

I would happily try this :)

**Comment by evant** [comment]
Thanks! this was definitely something we were exploring.

**Comment by FaustXVI** [comment]
Great ! Is there a branch I could look at ? Should I start one ?

**Comment by evant** [comment]
Go ahead and start one! Let me know if you want to discuss anything to get started.

**Comment by evant** [comment]
Published 0.11 which supports the jvm and js platforms. There's also experimental native support in the works https://github.com/willowtreeapps/assertk/pull/112
