### ISSUE TITLE
Consider adding a "block does not throw" variant

### ISSUE THREAD

**Issue by mkobit** [willowtreeapps/assertk#87]
AssertJ has the `assertThatCode(() -> {}).doesNotThrowAnyException();` which can be useful for 

This can sort of be done now by doing

```kotlin
assert {
  maybeThrowingMethod()
}.returnedValue {}
```

In my own project I'm just using `private fun <T> AssertBlock<T>.doesNotThrowAnyException() = returnedValue { }` 

But there might be a more idiomatic way to do it if it is desired as part of the library.

**Comment by evant** [comment]
Think adding
```
assert {
  maybeThrowingMethod()
}.doesNotThrowAnyException()
```
seems reasonable
