### ISSUE TITLE
Add isEmpty assertions to Map 

### ISSUE THREAD

**Issue by abyu** [willowtreeapps/assertk#91]
New assertions to Map to check if it's empty. Right I have to do something like 
assert(theMap.keys).isEmpty()

instead assert(theMap).isEmpty() would read better

**Comment by evant** [comment]
Agreed, this is planned.

**Comment by ntw222** [comment]
Can I contribute to this issue ?

**Comment by evant** [comment]
Implemented https://github.com/willowtreeapps/assertk/blob/master/assertk-common/src/main/kotlin/assertk/assertions/map.kt#L13
