### ISSUE TITLE
Feature Request: Add ability to do quantitative predicates for groups of objects

### ISSUE THREAD

**Issue by mkobit** [willowtreeapps/assertk#98]
I don't know the right way to describe the feature, but this is something I use all the time from AssertJ.

Some from [`ObjectEnumerableAssert`](https://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/ObjectEnumerableAssert.html) to demonstrate what I'm looking for:

* `areAtLeast(int n, Condition<? super ELEMENT> condition)`
* `areAtMost(int n, Condition<? super ELEMENT> condition)`
* `areExactly(int n, Condition<? super ELEMENT> condition)`
* `areNot(Condition<? super ELEMENT> condition)`
* `are(Condition<? super ELEMENT> condition)`

**Comment by evant** [comment]
Merged in `atLeast` with https://github.com/willowtreeapps/assertk/commit/87f01511b848529beec055feea4d1254c12ef3d7 think the pattern should work well for the similar methods.

**Comment by evant** [comment]
So `atLeast`, `atMost`, and `exactly` are implemented now. `each` has the same semantics as `are` and you can invert the assertions in `each` to get `areNot` ex:

```kotlin
assertThat(list).each {
   it.isNotEqualTo("foo")
}
```

this seem to cover these use-cases reasonably? I'm thinking we can close this issue now.
